import { Knex } from 'knex';

const tableName = 'country';

export async function seed(knex: Knex): Promise<void> {
  await knex(tableName).delete();
  return knex(tableName).insert([
    {
      id: 1,
      name: "Brazil",
      pt_name: "Brasil",
      abbr: "BR",
      bacen: 1058,
    },
    {
      id: 2,
      name: "Afghanistan",
      pt_name: "Afeganistão",
      abbr: "AF",
      bacen: 132,
    },
    {
      id: 3,
      name: "Albania",
      pt_name: "Albânia, Republica da",
      abbr: "AL",
      bacen: 175,
    },
    {
      id: 4,
      name: "Algeria",
      pt_name: "Argélia",
      abbr: "DZ",
      bacen: 590,
    },
    {
      id: 5,
      name: "American Samoa",
      pt_name: "Samoa Americana",
      abbr: "AS",
      bacen: 6912,
    },
    {
      id: 6,
      name: "Andorra",
      pt_name: "Andorra",
      abbr: "AD",
      bacen: 370,
    },
    {
      id: 7,
      name: "Angola",
      pt_name: "Angola",
      abbr: "AO",
      bacen: 400,
    },
    {
      id: 8,
      name: "Anguilla",
      pt_name: "Anguilla",
      abbr: "AI",
      bacen: 418,
    },
    {
      id: 9,
      name: "Antarctica",
      pt_name: "Antártida",
      abbr: "AQ",
      bacen: 3596,
    },
    {
      id: 10,
      name: "Antigua and Barbuda",
      pt_name: "Antigua e Barbuda",
      abbr: "AG",
      bacen: 434,
    },
    {
      id: 11,
      name: "Argentina",
      pt_name: "Argentina",
      abbr: "AR",
      bacen: 639,
    },
    {
      id: 12,
      name: "Armenia",
      pt_name: "Armênia, Republica da",
      abbr: "AM",
      bacen: 647,
    },
    {
      id: 13,
      name: "Aruba",
      pt_name: "Aruba",
      abbr: "AW",
      bacen: 655,
    },
    {
      id: 14,
      name: "Australia",
      pt_name: "Austrália",
      abbr: "AU",
      bacen: 698,
    },
    {
      id: 15,
      name: "Austria",
      pt_name: "Áustria",
      abbr: "AT",
      bacen: 728,
    },
    {
      id: 16,
      name: "Azerbaijan",
      pt_name: "Azerbaijão, Republica do",
      abbr: "AZ",
      bacen: 736,
    },
    {
      id: 17,
      name: "Bahamas",
      pt_name: "Bahamas, Ilhas",
      abbr: "BS",
      bacen: 779,
    },
    {
      id: 18,
      name: "Bahrain",
      pt_name: "Bahrein, Ilhas",
      abbr: "BH",
      bacen: 809,
    },
    {
      id: 19,
      name: "Bangladesh",
      pt_name: "Bangladesh",
      abbr: "BD",
      bacen: 817,
    },
    {
      id: 20,
      name: "Barbados",
      pt_name: "Barbados",
      abbr: "BB",
      bacen: 833,
    },
    {
      id: 21,
      name: "Belarus",
      pt_name: "Belarus, Republica da",
      abbr: "BY",
      bacen: 850,
    },
    {
      id: 22,
      name: "Belgium",
      pt_name: "Bélgica",
      abbr: "BE",
      bacen: 876,
    },
    {
      id: 23,
      name: "Belize",
      pt_name: "Belize",
      abbr: "BZ",
      bacen: 884,
    },
    {
      id: 24,
      name: "Benin",
      pt_name: "Benin",
      abbr: "BJ",
      bacen: 2291,
    },
    {
      id: 25,
      name: "Bermuda",
      pt_name: "Bermudas",
      abbr: "BM",
      bacen: 906,
    },
    {
      id: 26,
      name: "Bhutan",
      pt_name: "Butão",
      abbr: "BT",
      bacen: 1198,
    },
    {
      id: 27,
      name: "Bolivia",
      pt_name: "Bolívia",
      abbr: "BO",
      bacen: 973,
    },
    {
      id: 28,
      name: "Bosnia and Herzegowina",
      pt_name: "Bósnia-herzegovina (Republica da)",
      abbr: "BA",
      bacen: 981,
    },
    {
      id: 29,
      name: "Botswana",
      pt_name: "Botsuana",
      abbr: "BW",
      bacen: 1015,
    },
    {
      id: 30,
      name: "Bouvet Island",
      pt_name: "Bouvet, Ilha",
      abbr: "BV",
      bacen: 1023,
    },
    {
      id: 31,
      name: "British Indian Ocean Territory",
      pt_name: "Território Britânico do Oceano Indico",
      abbr: "IO",
      bacen: 7820,
    },
    {
      id: 32,
      name: "Brunei Darussalam",
      pt_name: "Brunei",
      abbr: "BN",
      bacen: 1082,
    },
    {
      id: 33,
      name: "Bulgaria",
      pt_name: "Bulgária, Republica da",
      abbr: "BG",
      bacen: 1112,
    },
    {
      id: 34,
      name: "Burkina Faso",
      pt_name: "Burkina Faso",
      abbr: "BF",
      bacen: 310,
    },
    {
      id: 35,
      name: "Burundi",
      pt_name: "Burundi",
      abbr: "BI",
      bacen: 1155,
    },
    {
      id: 36,
      name: "Cambodia",
      pt_name: "Camboja",
      abbr: "KH",
      bacen: 1414,
    },
    {
      id: 37,
      name: "Cameroon",
      pt_name: "Camarões",
      abbr: "CM",
      bacen: 1457,
    },
    {
      id: 38,
      name: "Canada",
      pt_name: "Canada",
      abbr: "CA",
      bacen: 1490,
    },
    {
      id: 39,
      name: "Cape Verde",
      pt_name: "Cabo Verde, Republica de",
      abbr: "CV",
      bacen: 1279,
    },
    {
      id: 40,
      name: "Cayman Islands",
      pt_name: "Cayman, Ilhas",
      abbr: "KY",
      bacen: 1376,
    },
    {
      id: 41,
      name: "Central African Republic",
      pt_name: "Republica Centro-Africana",
      abbr: "CF",
      bacen: 6408,
    },
    {
      id: 42,
      name: "Chad",
      pt_name: "Chade",
      abbr: "TD",
      bacen: 7889,
    },
    {
      id: 43,
      name: "Chile",
      pt_name: "Chile",
      abbr: "CL",
      bacen: 1589,
    },
    {
      id: 44,
      name: "China",
      pt_name: "China, Republica Popular",
      abbr: "CN",
      bacen: 1600,
    },
    {
      id: 45,
      name: "Christmas Island",
      pt_name: "Christmas, Ilha (Navidad)",
      abbr: "CX",
      bacen: 5118,
    },
    {
      id: 46,
      name: "Cocos (Keeling) Islands",
      pt_name: "Cocos (Keeling), Ilhas",
      abbr: "CC",
      bacen: 1651,
    },
    {
      id: 47,
      name: "Colombia",
      pt_name: "Colômbia",
      abbr: "CO",
      bacen: 1694,
    },
    {
      id: 48,
      name: "Comoros",
      pt_name: "Comores, Ilhas",
      abbr: "KM",
      bacen: 1732,
    },
    {
      id: 49,
      name: "Congo",
      pt_name: "Congo",
      abbr: "CG",
      bacen: 1775,
    },
    {
      id: 50,
      name: "Congo, the Democratic Republic of the",
      pt_name: "Congo, Republica Democrática do",
      abbr: "CD",
      bacen: 8885,
    },
    {
      id: 51,
      name: "Cook Islands",
      pt_name: "Cook, Ilhas",
      abbr: "CK",
      bacen: 1830,
    },
    {
      id: 52,
      name: "Costa Rica",
      pt_name: "Costa Rica",
      abbr: "CR",
      bacen: 1961,
    },
    {
      id: 53,
      name: "Cote d`Ivoire",
      pt_name: "Costa do Marfim",
      abbr: "CI",
      bacen: 1937,
    },
    {
      id: 54,
      name: "Croatia (Hrvatska)",
      pt_name: "Croácia (Republica da)",
      abbr: "HR",
      bacen: 1953,
    },
    {
      id: 55,
      name: "Cuba",
      pt_name: "Cuba",
      abbr: "CU",
      bacen: 1996,
    },
    {
      id: 56,
      name: "Cyprus",
      pt_name: "Chipre",
      abbr: "CY",
      bacen: 1635,
    },
    {
      id: 57,
      name: "Czech Republic",
      pt_name: "Tcheca, Republica",
      abbr: "CZ",
      bacen: 7919,
    },
    {
      id: 58,
      name: "Denmark",
      pt_name: "Dinamarca",
      abbr: "DK",
      bacen: 2321,
    },
    {
      id: 59,
      name: "Djibouti",
      pt_name: "Djibuti",
      abbr: "DJ",
      bacen: 7838,
    },
    {
      id: 60,
      name: "Dominica",
      pt_name: "Dominica, Ilha",
      abbr: "DM",
      bacen: 2356,
    },
    {
      id: 61,
      name: "Dominican Republic",
      pt_name: "Republica Dominicana",
      abbr: "DO",
      bacen: 6475,
    },
    {
      id: 62,
      name: "East Timor",
      pt_name: "Timor Leste",
      abbr: "TL",
      bacen: 7951,
    },
    {
      id: 63,
      name: "Ecuador",
      pt_name: "Equador",
      abbr: "EC",
      bacen: 2399,
    },
    {
      id: 64,
      name: "Egypt",
      pt_name: "Egito",
      abbr: "EG",
      bacen: 2402,
    },
    {
      id: 65,
      name: "El Salvador",
      pt_name: "El Salvador",
      abbr: "SV",
      bacen: 6874,
    },
    {
      id: 66,
      name: "Equatorial Guinea",
      pt_name: "Guine-Equatorial",
      abbr: "GQ",
      bacen: 3310,
    },
    {
      id: 67,
      name: "Eritrea",
      pt_name: "Eritreia",
      abbr: "ER",
      bacen: 2437,
    },
    {
      id: 68,
      name: "Estonia",
      pt_name: "Estônia, Republica da",
      abbr: "EE",
      bacen: 2518,
    },
    {
      id: 69,
      name: "Ethiopia",
      pt_name: "Etiópia",
      abbr: "ET",
      bacen: 2534,
    },
    {
      id: 70,
      name: "Falkland Islands (Malvinas)",
      pt_name: "Falkland (Ilhas Malvinas)",
      abbr: "FK",
      bacen: 2550,
    },
    {
      id: 71,
      name: "Faroe Islands",
      pt_name: "Feroe, Ilhas",
      abbr: "FO",
      bacen: 2593,
    },
    {
      id: 72,
      name: "Fiji",
      pt_name: "Fiji",
      abbr: "FJ",
      bacen: 8702,
    },
    {
      id: 73,
      name: "Finland",
      pt_name: "Finlândia",
      abbr: "FI",
      bacen: 2712,
    },
    {
      id: 74,
      name: "France",
      pt_name: "Franca",
      abbr: "FR",
      bacen: 2755,
    },
    {
      id: 76,
      name: "French Guiana",
      pt_name: "Guiana francesa",
      abbr: "GF",
      bacen: 3255,
    },
    {
      id: 77,
      name: "French Polynesia",
      pt_name: "Polinésia Francesa",
      abbr: "PF",
      bacen: 5991,
    },
    {
      id: 78,
      name: "French Southern Territories",
      pt_name: "Terras Austrais e Antárticas Francesas",
      abbr: "TF",
      bacen: 3607,
    },
    {
      id: 79,
      name: "Gabon",
      pt_name: "Gabão",
      abbr: "GA",
      bacen: 2810,
    },
    {
      id: 80,
      name: "Gambia",
      pt_name: "Gambia",
      abbr: "GM",
      bacen: 2852,
    },
    {
      id: 81,
      name: "Georgia",
      pt_name: "Georgia, Republica da",
      abbr: "GE",
      bacen: 2917,
    },
    {
      id: 82,
      name: "Germany",
      pt_name: "Alemanha",
      abbr: "DE",
      bacen: 230,
    },
    {
      id: 83,
      name: "Ghana",
      pt_name: "Gana",
      abbr: "GH",
      bacen: 2895,
    },
    {
      id: 84,
      name: "Gibraltar",
      pt_name: "Gibraltar",
      abbr: "GI",
      bacen: 2933,
    },
    {
      id: 85,
      name: "Greece",
      pt_name: "Grécia",
      abbr: "GR",
      bacen: 3018,
    },
    {
      id: 86,
      name: "Greenland",
      pt_name: "Groenlândia",
      abbr: "GL",
      bacen: 3050,
    },
    {
      id: 87,
      name: "Grenada",
      pt_name: "Granada",
      abbr: "GD",
      bacen: 2976,
    },
    {
      id: 88,
      name: "Guadeloupe",
      pt_name: "Guadalupe",
      abbr: "GP",
      bacen: 3093,
    },
    {
      id: 89,
      name: "Guam",
      pt_name: "Guam",
      abbr: "GU",
      bacen: 3131,
    },
    {
      id: 90,
      name: "Guatemala",
      pt_name: "Guatemala",
      abbr: "GT",
      bacen: 3174,
    },
    {
      id: 91,
      name: "Guinea",
      pt_name: "Guine",
      abbr: "GN",
      bacen: 3298,
    },
    {
      id: 92,
      name: "Guinea-Bissau",
      pt_name: "Guine-Bissau",
      abbr: "GW",
      bacen: 3344,
    },
    {
      id: 93,
      name: "Guyana",
      pt_name: "Guiana",
      abbr: "GY",
      bacen: 3379,
    },
    {
      id: 94,
      name: "Haiti",
      pt_name: "Haiti",
      abbr: "HT",
      bacen: 3417,
    },
    {
      id: 95,
      name: "Heard and Mc Donald Islands",
      pt_name: "Ilha Heard e Ilhas McDonald",
      abbr: "HM",
      bacen: 3603,
    },
    {
      id: 96,
      name: "Holy See (Vatican City State)",
      pt_name: "Vaticano, Estado da Cidade do",
      abbr: "VA",
      bacen: 8486,
    },
    {
      id: 97,
      name: "Honduras",
      pt_name: "Honduras",
      abbr: "HN",
      bacen: 3450,
    },
    {
      id: 98,
      name: "Hong Kong",
      pt_name: "Hong Kong",
      abbr: "HK",
      bacen: 3514,
    },
    {
      id: 99,
      name: "Hungary",
      pt_name: "Hungria, Republica da",
      abbr: "HU",
      bacen: 3557,
    },
    {
      id: 100,
      name: "Iceland",
      pt_name: "Islândia",
      abbr: "IS",
      bacen: 3794,
    },
    {
      id: 101,
      name: "India",
      pt_name: "Índia",
      abbr: "IN",
      bacen: 3611,
    },
    {
      id: 102,
      name: "Indonesia",
      pt_name: "Indonésia",
      abbr: "ID",
      bacen: 3654,
    },
    {
      id: 103,
      name: "Iran (Islamic Republic of)",
      pt_name: "Ira, Republica Islâmica do",
      abbr: "IR",
      bacen: 3727,
    },
    {
      id: 104,
      name: "Iraq",
      pt_name: "Iraque",
      abbr: "IQ",
      bacen: 3697,
    },
    {
      id: 105,
      name: "Ireland",
      pt_name: "Irlanda",
      abbr: "IE",
      bacen: 3751,
    },
    {
      id: 106,
      name: "Israel",
      pt_name: "Israel",
      abbr: "IL",
      bacen: 3832,
    },
    {
      id: 107,
      name: "Italy",
      pt_name: "Itália",
      abbr: "IT",
      bacen: 3867,
    },
    {
      id: 108,
      name: "Jamaica",
      pt_name: "Jamaica",
      abbr: "JM",
      bacen: 3913,
    },
    {
      id: 109,
      name: "Japan",
      pt_name: "Japão",
      abbr: "JP",
      bacen: 3999,
    },
    {
      id: 110,
      name: "Jordan",
      pt_name: "Jordânia",
      abbr: "JO",
      bacen: 4030,
    },
    {
      id: 111,
      name: "Kazakhstan",
      pt_name: "Cazaquistão, Republica do",
      abbr: "KZ",
      bacen: 1538,
    },
    {
      id: 112,
      name: "Kenya",
      pt_name: "Quênia",
      abbr: "KE",
      bacen: 6238,
    },
    {
      id: 113,
      name: "Kiribati",
      pt_name: "Kiribati",
      abbr: "KI",
      bacen: 4111,
    },
    {
      id: 114,
      name: "Korea, Democratic People`s Republic of",
      pt_name: "Coreia, Republica Popular Democrática da",
      abbr: "KP",
      bacen: 1872,
    },
    {
      id: 115,
      name: "Korea, Republic of",
      pt_name: "Coreia, Republica da",
      abbr: "KR",
      bacen: 1902,
    },
    {
      id: 116,
      name: "Kuwait",
      pt_name: "Kuwait",
      abbr: "KW",
      bacen: 1988,
    },
    {
      id: 117,
      name: "Kyrgyzstan",
      pt_name: "Quirguiz, Republica",
      abbr: "KG",
      bacen: 6254,
    },
    {
      id: 118,
      name: "Lao People`s Democratic Republic",
      pt_name: "Laos, Republica Popular Democrática do",
      abbr: "LA",
      bacen: 4200,
    },
    {
      id: 119,
      name: "Latvia",
      pt_name: "Letônia, Republica da",
      abbr: "LV",
      bacen: 4278,
    },
    {
      id: 120,
      name: "Lebanon",
      pt_name: "Líbano",
      abbr: "LB",
      bacen: 4316,
    },
    {
      id: 121,
      name: "Lesotho",
      pt_name: "Lesoto",
      abbr: "LS",
      bacen: 4260,
    },
    {
      id: 122,
      name: "Liberia",
      pt_name: "Libéria",
      abbr: "LR",
      bacen: 4340,
    },
    {
      id: 123,
      name: "Libyan Arab Jamahiriya",
      pt_name: "Líbia",
      abbr: "LY",
      bacen: 4383,
    },
    {
      id: 124,
      name: "Liechtenstein",
      pt_name: "Liechtenstein",
      abbr: "LI",
      bacen: 4405,
    },
    {
      id: 125,
      name: "Lithuania",
      pt_name: "Lituânia, Republica da",
      abbr: "LT",
      bacen: 4421,
    },
    {
      id: 126,
      name: "Luxembourg",
      pt_name: "Luxemburgo",
      abbr: "LU",
      bacen: 4456,
    },
    {
      id: 127,
      name: "Macau",
      pt_name: "Macau",
      abbr: "MO",
      bacen: 4472,
    },
    {
      id: 128,
      name: "North Macedonia",
      pt_name: "Macedônia do Norte",
      abbr: "MK",
      bacen: 4499,
    },
    {
      id: 129,
      name: "Madagascar",
      pt_name: "Madagascar",
      abbr: "MG",
      bacen: 4502,
    },
    {
      id: 130,
      name: "Malawi",
      pt_name: "Malavi",
      abbr: "MW",
      bacen: 4588,
    },
    {
      id: 131,
      name: "Malaysia",
      pt_name: "Malásia",
      abbr: "MY",
      bacen: 4553,
    },
    {
      id: 132,
      name: "Maldives",
      pt_name: "Maldivas",
      abbr: "MV",
      bacen: 4618,
    },
    {
      id: 133,
      name: "Mali",
      pt_name: "Mali",
      abbr: "ML",
      bacen: 4642,
    },
    {
      id: 134,
      name: "Malta",
      pt_name: "Malta",
      abbr: "MT",
      bacen: 4677,
    },
    {
      id: 135,
      name: "Marshall Islands",
      pt_name: "Marshall, Ilhas",
      abbr: "MH",
      bacen: 4766,
    },
    {
      id: 136,
      name: "Martinique",
      pt_name: "Martinica",
      abbr: "MQ",
      bacen: 4774,
    },
    {
      id: 137,
      name: "Mauritania",
      pt_name: "Mauritânia",
      abbr: "MR",
      bacen: 4880,
    },
    {
      id: 138,
      name: "Mauritius",
      pt_name: "Mauricio",
      abbr: "MU",
      bacen: 4855,
    },
    {
      id: 139,
      name: "Mayotte",
      pt_name: "Mayotte (Ilhas Francesas)",
      abbr: "YT",
      bacen: 4885,
    },
    {
      id: 140,
      name: "Mexico",
      pt_name: "México",
      abbr: "MX",
      bacen: 4936,
    },
    {
      id: 141,
      name: "Micronesia, Federated States of",
      pt_name: "Micronesia",
      abbr: "FM",
      bacen: 4995,
    },
    {
      id: 142,
      name: "Moldova, Republic of",
      pt_name: "Moldávia, Republica da",
      abbr: "MD",
      bacen: 4944,
    },
    {
      id: 143,
      name: "Monaco",
      pt_name: "Mônaco",
      abbr: "MC",
      bacen: 4952,
    },
    {
      id: 144,
      name: "Mongolia",
      pt_name: "Mongólia",
      abbr: "MN",
      bacen: 4979,
    },
    {
      id: 145,
      name: "Montserrat",
      pt_name: "Montserrat, Ilhas",
      abbr: "MS",
      bacen: 5010,
    },
    {
      id: 146,
      name: "Morocco",
      pt_name: "Marrocos",
      abbr: "MA",
      bacen: 4740,
    },
    {
      id: 147,
      name: "Mozambique",
      pt_name: "Moçambique",
      abbr: "MZ",
      bacen: 5053,
    },
    {
      id: 148,
      name: "Myanmar",
      pt_name: "Mianmar (Birmânia)",
      abbr: "MM",
      bacen: 930,
    },
    {
      id: 149,
      name: "Namibia",
      pt_name: "Namíbia",
      abbr: "NA",
      bacen: 5070,
    },
    {
      id: 150,
      name: "Nauru",
      pt_name: "Nauru",
      abbr: "NR",
      bacen: 5088,
    },
    {
      id: 151,
      name: "Nepal",
      pt_name: "Nepal",
      abbr: "NP",
      bacen: 5177,
    },
    {
      id: 152,
      name: "Netherlands",
      pt_name: "Países Baixos (Holanda)",
      abbr: "NL",
      bacen: 5738,
    },
    {
      id: 154,
      name: "New Caledonia",
      pt_name: "Nova Caledonia",
      abbr: "NC",
      bacen: 5428,
    },
    {
      id: 155,
      name: "New Zealand",
      pt_name: "Nova Zelândia",
      abbr: "NZ",
      bacen: 5487,
    },
    {
      id: 156,
      name: "Nicaragua",
      pt_name: "Nicarágua",
      abbr: "NI",
      bacen: 5215,
    },
    {
      id: 157,
      name: "Niger",
      pt_name: "Níger",
      abbr: "NE",
      bacen: 5258,
    },
    {
      id: 158,
      name: "Nigeria",
      pt_name: "Nigéria",
      abbr: "NG",
      bacen: 5282,
    },
    {
      id: 159,
      name: "Niue",
      pt_name: "Niue, Ilha",
      abbr: "NU",
      bacen: 5312,
    },
    {
      id: 160,
      name: "Norfolk Island",
      pt_name: "Norfolk, Ilha",
      abbr: "NF",
      bacen: 5355,
    },
    {
      id: 161,
      name: "Northern Mariana Islands",
      pt_name: "Marianas do Norte",
      abbr: "MP",
      bacen: 4723,
    },
    {
      id: 162,
      name: "Norway",
      pt_name: "Noruega",
      abbr: "NO",
      bacen: 5380,
    },
    {
      id: 163,
      name: "Oman",
      pt_name: "Oma",
      abbr: "OM",
      bacen: 5568,
    },
    {
      id: 164,
      name: "Pakistan",
      pt_name: "Paquistão",
      abbr: "PK",
      bacen: 5762,
    },
    {
      id: 165,
      name: "Palau",
      pt_name: "Palau",
      abbr: "PW",
      bacen: 5754,
    },
    {
      id: 166,
      name: "Panama",
      pt_name: "Panamá",
      abbr: "PA",
      bacen: 5800,
    },
    {
      id: 167,
      name: "Papua New Guinea",
      pt_name: "Papua Nova Guine",
      abbr: "PG",
      bacen: 5452,
    },
    {
      id: 168,
      name: "Paraguay",
      pt_name: "Paraguai",
      abbr: "PY",
      bacen: 5860,
    },
    {
      id: 169,
      name: "Peru",
      pt_name: "Peru",
      abbr: "PE",
      bacen: 5894,
    },
    {
      id: 170,
      name: "Philippines",
      pt_name: "Filipinas",
      abbr: "PH",
      bacen: 2674,
    },
    {
      id: 171,
      name: "Pitcairn",
      pt_name: "Pitcairn, Ilha",
      abbr: "PN",
      bacen: 5932,
    },
    {
      id: 172,
      name: "Poland",
      pt_name: "Polônia, Republica da",
      abbr: "PL",
      bacen: 6033,
    },
    {
      id: 173,
      name: "Portugal",
      pt_name: "Portugal",
      abbr: "PT",
      bacen: 6076,
    },
    {
      id: 174,
      name: "Puerto Rico",
      pt_name: "Porto Rico",
      abbr: "PR",
      bacen: 6114,
    },
    {
      id: 175,
      name: "Qatar",
      pt_name: "Catar",
      abbr: "QA",
      bacen: 1546,
    },
    {
      id: 176,
      name: "Reunion",
      pt_name: "Reunião, Ilha",
      abbr: "RE",
      bacen: 6602,
    },
    {
      id: 177,
      name: "Romania",
      pt_name: "Romênia",
      abbr: "RO",
      bacen: 6700,
    },
    {
      id: 178,
      name: "Russian Federation",
      pt_name: "Rússia, Federação da",
      abbr: "RU",
      bacen: 6769,
    },
    {
      id: 179,
      name: "Rwanda",
      pt_name: "Ruanda",
      abbr: "RW",
      bacen: 6750,
    },
    {
      id: 180,
      name: "Saint Kitts and Nevis",
      pt_name: "São Cristovão e Neves, Ilhas",
      abbr: "KN",
      bacen: 6955,
    },
    {
      id: 181,
      name: "Saint LUCIA",
      pt_name: "Santa Lucia",
      abbr: "LC",
      bacen: 7153,
    },
    {
      id: 182,
      name: "Saint Vincent and the Grenadines",
      pt_name: "São Vicente e Granadinas",
      abbr: "VC",
      bacen: 7056,
    },
    {
      id: 183,
      name: "Samoa",
      pt_name: "Samoa",
      abbr: "WS",
      bacen: 6904,
    },
    {
      id: 184,
      name: "San Marino",
      pt_name: "San Marino",
      abbr: "SM",
      bacen: 6971,
    },
    {
      id: 185,
      name: "Sao Tome and Principe",
      pt_name: "São Tome e Príncipe, Ilhas",
      abbr: "ST",
      bacen: 7200,
    },
    {
      id: 186,
      name: "Saudi Arabia",
      pt_name: "Arábia Saudita",
      abbr: "SA",
      bacen: 531,
    },
    {
      id: 187,
      name: "Senegal",
      pt_name: "Senegal",
      abbr: "SN",
      bacen: 7285,
    },
    {
      id: 188,
      name: "Seychelles",
      pt_name: "Seychelles",
      abbr: "SC",
      bacen: 7315,
    },
    {
      id: 189,
      name: "Sierra Leone",
      pt_name: "Serra Leoa",
      abbr: "SL",
      bacen: 7358,
    },
    {
      id: 190,
      name: "Singapore",
      pt_name: "Cingapura",
      abbr: "SG",
      bacen: 7412,
    },
    {
      id: 191,
      name: "Slovakia (Slovak Republic)",
      pt_name: "Eslovaca, Republica",
      abbr: "SK",
      bacen: 2470,
    },
    {
      id: 192,
      name: "Slovenia",
      pt_name: "Eslovênia, Republica da",
      abbr: "SI",
      bacen: 2461,
    },
    {
      id: 193,
      name: "Solomon Islands",
      pt_name: "Salomão, Ilhas",
      abbr: "SB",
      bacen: 6777,
    },
    {
      id: 194,
      name: "Somalia",
      pt_name: "Somalia",
      abbr: "SO",
      bacen: 7480,
    },
    {
      id: 195,
      name: "South Africa",
      pt_name: "África do Sul",
      abbr: "ZA",
      bacen: 7560,
    },
    {
      id: 196,
      name: "South Georgia and the South Sandwich Islands",
      pt_name: "Ilhas Geórgia do Sul e Sandwich do Sul",
      abbr: "GS",
      bacen: 2925,
    },
    {
      id: 197,
      name: "Spain",
      pt_name: "Espanha",
      abbr: "ES",
      bacen: 2453,
    },
    {
      id: 198,
      name: "Sri Lanka",
      pt_name: "Sri Lanka",
      abbr: "LK",
      bacen: 7501,
    },
    {
      id: 199,
      name: "St. Helena",
      pt_name: "Santa Helena",
      abbr: "SH",
      bacen: 7102,
    },
    {
      id: 200,
      name: "St. Pierre and Miquelon",
      pt_name: "São Pedro e Miquelon",
      abbr: "PM",
      bacen: 7005,
    },
    {
      id: 201,
      name: "Sudan",
      pt_name: "Sudão",
      abbr: "SD",
      bacen: 7595,
    },
    {
      id: 202,
      name: "Suriname",
      pt_name: "Suriname",
      abbr: "SR",
      bacen: 7706,
    },
    {
      id: 203,
      name: "Svalbard and Jan Mayen Islands",
      pt_name: "Svalbard e Jan Mayen",
      abbr: "SJ",
      bacen: 7552,
    },
    {
      id: 204,
      name: "Swaziland",
      pt_name: "Eswatini",
      abbr: "SZ",
      bacen: 7544,
    },
    {
      id: 205,
      name: "Sweden",
      pt_name: "Suécia",
      abbr: "SE",
      bacen: 7641,
    },
    {
      id: 206,
      name: "Switzerland",
      pt_name: "Suíça",
      abbr: "CH",
      bacen: 7676,
    },
    {
      id: 207,
      name: "Syrian Arab Republic",
      pt_name: "Síria, Republica Árabe da",
      abbr: "SY",
      bacen: 7447,
    },
    {
      id: 208,
      name: "Taiwan, Province of China",
      pt_name: "Formosa (Taiwan)",
      abbr: "TW",
      bacen: 1619,
    },
    {
      id: 209,
      name: "Tajikistan",
      pt_name: "Tadjiquistao, Republica do",
      abbr: "TJ",
      bacen: 7722,
    },
    {
      id: 210,
      name: "Tanzania, United Republic of",
      pt_name: "Tanzânia, Republica Unida da",
      abbr: "TZ",
      bacen: 7803,
    },
    {
      id: 211,
      name: "Thailand",
      pt_name: "Tailândia",
      abbr: "TH",
      bacen: 7765,
    },
    {
      id: 212,
      name: "Togo",
      pt_name: "Togo",
      abbr: "TG",
      bacen: 8001,
    },
    {
      id: 213,
      name: "Tokelau",
      pt_name: "Toquelau, Ilhas",
      abbr: "TK",
      bacen: 8052,
    },
    {
      id: 214,
      name: "Tonga",
      pt_name: "Tonga",
      abbr: "TO",
      bacen: 8109,
    },
    {
      id: 215,
      name: "Trinidad and Tobago",
      pt_name: "Trinidad e Tobago",
      abbr: "TT",
      bacen: 8150,
    },
    {
      id: 216,
      name: "Tunisia",
      pt_name: "Tunísia",
      abbr: "TN",
      bacen: 8206,
    },
    {
      id: 217,
      name: "Turkey",
      pt_name: "Turquia",
      abbr: "TR",
      bacen: 8273,
    },
    {
      id: 218,
      name: "Turkmenistan",
      pt_name: "Turcomenistão, Republica do",
      abbr: "TM",
      bacen: 8249,
    },
    {
      id: 219,
      name: "Turks and Caicos Islands",
      pt_name: "Turcas e Caicos, Ilhas",
      abbr: "TC",
      bacen: 8230,
    },
    {
      id: 220,
      name: "Tuvalu",
      pt_name: "Tuvalu",
      abbr: "TV",
      bacen: 8281,
    },
    {
      id: 221,
      name: "Uganda",
      pt_name: "Uganda",
      abbr: "UG",
      bacen: 8338,
    },
    {
      id: 222,
      name: "Ukraine",
      pt_name: "Ucrânia",
      abbr: "UA",
      bacen: 8311,
    },
    {
      id: 223,
      name: "United Arab Emirates",
      pt_name: "Emirados Árabes Unidos",
      abbr: "AE",
      bacen: 2445,
    },
    {
      id: 224,
      name: "United Kingdom",
      pt_name: "Reino Unido",
      abbr: "GB",
      bacen: 6289,
    },
    {
      id: 225,
      name: "United States",
      pt_name: "Estados Unidos",
      abbr: "US",
      bacen: 2496,
    },
    {
      id: 226,
      name: "United States Minor Outlying Islands",
      pt_name: "Ilhas Menores Distantes dos Estados Unidos",
      abbr: "UM",
      bacen: 18664,
    },
    {
      id: 227,
      name: "Uruguay",
      pt_name: "Uruguai",
      abbr: "UY",
      bacen: 8451,
    },
    {
      id: 228,
      name: "Uzbekistan",
      pt_name: "Uzbequistão, Republica do",
      abbr: "UZ",
      bacen: 8478,
    },
    {
      id: 229,
      name: "Vanuatu",
      pt_name: "Vanuatu",
      abbr: "VU",
      bacen: 5517,
    },
    {
      id: 230,
      name: "Venezuela",
      pt_name: "Venezuela",
      abbr: "VE",
      bacen: 8508,
    },
    {
      id: 231,
      name: "Viet Nam",
      pt_name: "Vietnã",
      abbr: "VN",
      bacen: 8583,
    },
    {
      id: 232,
      name: "Virgin Islands (British)",
      pt_name: "Virgens, Ilhas (Britânicas)",
      abbr: "VG",
      bacen: 8630,
    },
    {
      id: 233,
      name: "Virgin Islands (U.S.)",
      pt_name: "Virgens, Ilhas (E.U.A.)",
      abbr: "VI",
      bacen: 8664,
    },
    {
      id: 234,
      name: "Wallis and Futuna Islands",
      pt_name: "Wallis e Futuna, Ilhas",
      abbr: "WF",
      bacen: 8753,
    },
    {
      id: 235,
      name: "Western Sahara",
      pt_name: "Saara Ocidental",
      abbr: "EH",
      bacen: 6858,
    },
    {
      id: 236,
      name: "Yemen",
      pt_name: "Iémen",
      abbr: "YE",
      bacen: 3573,
    },
    {
      id: 237,
      name: "Yugoslavia",
      pt_name: "Iugoslávia, República Fed. da",
      abbr: "YU",
      bacen: 3883,
    },
    {
      id: 238,
      name: "Zambia",
      pt_name: "Zâmbia",
      abbr: "ZM",
      bacen: 8907,
    },
    {
      id: 239,
      name: "Zimbabwe",
      pt_name: "Zimbabue",
      abbr: "ZW",
      bacen: 6653,
    },
    {
      id: 240,
      name: "Bailiwick of Guernsey",
      pt_name: "Guernsey, Ilha do Canal (Inclui Alderney e Sark)",
      abbr: "GG",
      bacen: 1504,
    },
    {
      id: 241,
      name: "Bailiwick of Jersey",
      pt_name: "Jersey, Ilha do Canal",
      abbr: "JE",
      bacen: 1508,
    },
    {
      id: 243,
      name: "Isle of Man",
      pt_name: "Man, Ilha de",
      abbr: "IM",
      bacen: 3595,
    },
    {
      id: 246,
      name: "Crna Gora (Montenegro)",
      pt_name: "Montenegro",
      abbr: "ME",
      bacen: 4985,
    },
    {
      id: 247,
      name: "SÉRVIA",
      pt_name: "Republika Srbija",
      abbr: "RS",
      bacen: 7370,
    },
    {
      id: 248,
      name: "Republic of South Sudan",
      pt_name: "Sudao do Sul",
      abbr: "SS",
      bacen: 7600,
    },
    {
      id: 249,
      name: "Zona del Canal de Panamá",
      pt_name: "Zona do Canal do Panamá",
      abbr: null,
      bacen: 8958,
    },
    {
      id: 252,
      name: "Dawlat Filasṭīn",
      pt_name: "Palestina",
      abbr: "PS",
      bacen: 5780,
    },
    {
      id: 253,
      name: "Åland Islands",
      pt_name: "Aland, Ilhas",
      abbr: "AX",
      bacen: 153,
    },
    {
      id: 255,
      name: "Curaçao",
      pt_name: "Curaçao",
      abbr: "CW",
      bacen: 200,
    },
    {
      id: 256,
      name: "Saint Martin",
      pt_name: "São Martinho, Ilha de (Parte Holandesa)",
      abbr: "SM",
      bacen: 6998,
    },
    {
      id: 258,
      name: "Bonaire",
      pt_name: "Bonaire",
      abbr: "AN",
      bacen: 990,
    },
    {
      id: 259,
      name: "Antartica",
      pt_name: "Antartica",
      abbr: "AQ",
      bacen: 420,
    },
    {
      id: 260,
      name: "Heard Island and McDonald Islands",
      pt_name: "Ilha Herad e Ilhas Macdonald",
      abbr: "AU",
      bacen: 3433,
    },
    {
      id: 261,
      name: "Saint-Barthélemy",
      pt_name: "São Bartolomeu",
      abbr: "FR",
      bacen: 6939,
    },
    {
      id: 262,
      name: "Saint Martin",
      pt_name: "São Martinho, Ilha de (Parte Francesa)",
      abbr: "SM",
      bacen: 6980,
    },
    {
      id: 263,
      name: "Terres Australes et Antarctiques Françaises",
      pt_name: "Terras Austrais e Antárcticas Francesas",
      abbr: "TF",
      bacen: 7811,
    },
  ]);
}
