import { Knex } from "knex";

const tableName = "state";

export async function seed(knex: Knex): Promise<void> {
  await knex(tableName).delete();
  return knex(tableName).insert([
    {
      id: 1,
      name: "Acre",
      abbr: "AC",
      ibge_code: 12,
      country_id: 1,
      ddd: 68,
    },
    {
      id: 2,
      name: "Alagoas",
      abbr: "AL",
      ibge_code: 27,
      country_id: 1,
      ddd: 82,
    },
    {
      id: 3,
      name: "Amazonas",
      abbr: "AM",
      ibge_code: 13,
      country_id: 1,
      ddd: "97,92",
    },
    {
      id: 4,
      name: "Amapá",
      abbr: "AP",
      ibge_code: 16,
      country_id: 1,
      ddd: 96,
    },
    {
      id: 5,
      name: "Bahia",
      abbr: "BA",
      ibge_code: 29,
      country_id: 1,
      ddd: "77,75,73,74,71",
    },
    {
      id: 6,
      name: "Ceará",
      abbr: "CE",
      ibge_code: 23,
      country_id: 1,
      ddd: "88,85",
    },
    {
      id: 7,
      name: "Distrito Federal",
      abbr: "DF",
      ibge_code: 53,
      country_id: 1,
      ddd: 61,
    },
    {
      id: 8,
      name: "Espírito Santo",
      abbr: "ES",
      ibge_code: 32,
      country_id: 1,
      ddd: "28,27",
    },
    {
      id: 9,
      name: "Goiás",
      abbr: "GO",
      ibge_code: 52,
      country_id: 1,
      ddd: "62,64,61",
    },
    {
      id: 10,
      name: "Maranhão",
      abbr: "MA",
      ibge_code: 21,
      country_id: 1,
      ddd: "99,98",
    },
    {
      id: 11,
      name: "Minas Gerais",
      abbr: "MG",
      ibge_code: 31,
      country_id: 1,
      ddd: "34,37,31,33,35,38,32",
    },
    {
      id: 12,
      name: "Mato Grosso do Sul",
      abbr: "MS",
      ibge_code: 50,
      country_id: 1,
      ddd: 67,
    },
    {
      id: 13,
      name: "Mato Grosso",
      abbr: "MT",
      ibge_code: 51,
      country_id: 1,
      ddd: "65,66",
    },
    {
      id: 14,
      name: "Pará",
      abbr: "PA",
      ibge_code: 15,
      country_id: 1,
      ddd: "91,94,93",
    },
    {
      id: 15,
      name: "Paraíba",
      abbr: "PB",
      ibge_code: 25,
      country_id: 1,
      ddd: 83,
    },
    {
      id: 16,
      name: "Pernambuco",
      abbr: "PE",
      ibge_code: 26,
      country_id: 1,
      ddd: "81,87",
    },
    {
      id: 17,
      name: "Piauí",
      abbr: "PI",
      ibge_code: 22,
      country_id: 1,
      ddd: "89,86",
    },
    {
      id: 18,
      name: "Paraná",
      abbr: "PR",
      ibge_code: 41,
      country_id: 1,
      ddd: "43,41,42,44,45,46",
    },
    {
      id: 19,
      name: "Rio de Janeiro",
      abbr: "RJ",
      ibge_code: 33,
      country_id: 1,
      ddd: "24,22,21",
    },
    {
      id: 20,
      name: "Rio Grande do Norte",
      abbr: "RN",
      ibge_code: 24,
      country_id: 1,
      ddd: 84,
    },
    {
      id: 21,
      name: "Rondônia",
      abbr: "RO",
      ibge_code: 11,
      country_id: 1,
      ddd: 69,
    },
    {
      id: 22,
      name: "Roraima",
      abbr: "RR",
      ibge_code: 14,
      country_id: 1,
      ddd: 95,
    },
    {
      id: 23,
      name: "Rio Grande do Sul",
      abbr: "RS",
      ibge_code: 43,
      country_id: 1,
      ddd: "53,54,55,51",
    },
    {
      id: 24,
      name: "Santa Catarina",
      abbr: "SC",
      ibge_code: 42,
      country_id: 1,
      ddd: "47,48,49",
    },
    {
      id: 25,
      name: "Sergipe",
      abbr: "SE",
      ibge_code: 28,
      country_id: 1,
      ddd: 79,
    },
    {
      id: 26,
      name: "São Paulo",
      abbr: "SP",
      ibge_code: 35,
      country_id: 1,
      ddd: "11,12,13,14,15,16,17,18,19",
    },
    {
      id: 27,
      name: "Tocantins",
      abbr: "TO",
      ibge_code: 17,
      country_id: 1,
      ddd: 63,
    },
    {
      id: 99,
      name: "Exterior",
      abbr: "EX",
      ibge_code: 99,
      country_id: null,
      ddd: null,
    },
  ]);
}
